name: Publish Python distributions to PyPI

on:
  release:
    types: [published]

env:
  PACKAGE_NAME: exchange_calendars_extensions_api
  MODULE_NAME: exchange_calendars_extensions.api

jobs:
  build-and-publish:
    name: Build and publish Python distributions to TestPyPI and PyPI.
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry.
      run: pipx install poetry
    - name: Set up Python 3.10.
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'poetry'
    - name: Set poetry package version from tag.
      run: poetry version ${{ github.ref_name }}
    - name: Determine path to version.py from module name.
      run: |
          export VERSION_PATH=$(echo ${{ env.MODULE_NAME }} | sed 's/\./\//g')/version.py
          echo "VERSION_PATH=VERSION_PATH" >> $GITHUB_ENV
    - name: Generate version.py
      run: |
          echo "version = '${{ github.ref_name }}'" > ${{ env.VERSION_PATH }}
    - name: Generate requirements.txt.
      run: poetry export -f requirements.txt --without-hashes > requirements.txt
    - name: Build package with poetry.
      run: poetry build
    - name: Publish package to Test PyPI.
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
    - name: Install from testpypi and import.
      run: |
        i=0
        while (($i<120)) && [[ ! $(curl --max-time 120 -s https://test.pypi.org/pypi/${{ env.PACKAGE_NAME }}/json | jq -r '.releases | keys[]') =~ (^|[[:space:]])${{ github.ref_name }}($|[[:space:]]) ]];\
          do echo waiting for package to appear in test index, sleeping 5s; sleep 5s; let i++; done
        pip install --no-cache-dir --index-url https://test.pypi.org/simple ${{ env.PACKAGE_NAME }}==${{ github.ref_name }} --no-deps
        pip install -r requirements.txt
        python -c 'import ${{ env.MODULE_NAME }};print(${{ env.MODULE_NAME }}.__version__)'
    - name: Clean pip
      run: |
        pip uninstall -y ${{ env.PACKAGE_NAME }}
        pip cache purge
    - name: Publish package to PyPI.
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
    - name: Install and import.
      run: |
        i=0
        while (($i<120)) && [[ ! $(curl --max-time 120 -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json | jq -r '.releases | keys[]') =~ (^|[[:space:]])${{ github.ref_name }}($|[[:space:]]) ]];\
          do echo waiting for package to appear in index, sleeping 5s; sleep 5s; let i++; done
        pip install --no-cache-dir --index-url https://pypi.org/simple ${{ env.PACKAGE_NAME }}==${{ github.ref_name }}
        python -c 'import ${{ env.MODULE_NAME }};print(${{ env.MODULE_NAME }}.__version__)'
